export const GET_FAVORITE_COLOR_REQUEST = "GET_FAVORITE_COLOR_REQUEST";
export const GET_FAVORITE_COLOR_SUCCESS = "GET_FAVORITE_COLOR_SUCCESS";
export const GET_FAVORITE_COLOR_FAILURE = "GET_FAVORITE_COLOR_FAILURE";